version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourusername/yourapp:latest
    container_name: sample-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped