name: Docker Security Scan

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name (e.g., user/app:tag)'
        required: true
        type: string

jobs:
  scan-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Download the Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image_name }}
          format: table
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ inputs.image_name }}
