# .github/workflows/docker-security-scan.yml
name: Docker Security Scan

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name (including tag)'
        required: true
      tar_file:
        description: 'Path to the tar file containing the image'
        required: true

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Load Docker image
        run: |
          # Create a directory for the tar file
          mkdir -p /tmp/docker-images
          # Copy the tar file to the runner
          cp ${{ github.event.inputs.tar_file }} /tmp/docker-images/image.tar
          # Load the image
          docker load -i /tmp/docker-images/image.tar
          # Verify the image is loaded
          docker image ls

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.event.inputs.image_name }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.txt'

      - name: Upload Trivy scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.txt

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Push to Docker Hub
        if: success()
        run: |
          echo "Pushing image to Docker Hub..."
          docker push ${{ github.event.inputs.image_name }}
          echo "Image successfully pushed to Docker Hub!"