# .github/workflows/docker-security-scan.yml
name: Docker Security Scan

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name (including tag)'
        required: true
      branch_name:
        description: 'Branch containing the Docker image'
        required: true

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Load Docker image
        run: |
          # Build the image from the temporary Dockerfile that loads the tar
          docker build -t ${{ github.event.inputs.image_name }} .
          # Verify the image is loaded
          docker image ls ${{ github.event.inputs.image_name }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.event.inputs.image_name }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.txt'

      - name: Upload Trivy scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.txt